{% set name = "gms_preprocessing" %}
{% set version = "0.18.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gms_preprocessing-{{ version }}.tar.gz
  sha256: 4623f108094da8465c483bbb860d4312ab7e9919f9e02852a2b224ca76ed96c7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - arosics >=1.0.0
    - cerberus
    - dill
    - ephem
    - gdal
    - geoalchemy2
    - geoarray >=0.9.0
    - geopandas
    - iso8601
    - jsmin
    - matplotlib-base
    - natsort
    - nested_dict
    - numpy
    - openpyxl
    - pandas
    - psutil
    - psycopg2
    - py-tools-ds >=0.12.4
    - pyhdf
    - pyinstrument
    - pyorbital
    - pyproj
    - pyrsr >=0.3.1
    - python
    - python-fmask
    - pytz
    - redis-py  # named redis on PyPI and redis-py on conda-forge; importable as 'redis'
    - redis-semaphore
    - retools
    - scikit-learn
    - scipy
    - shapely
    - sicor
    - spechomo
    - spectral >=0.16
    - sqlalchemy
    - timeout-decorator
    - tqdm

test:
  imports:
    - gms_preprocessing
    - gms_preprocessing.algorithms
    - gms_preprocessing.io
    - gms_preprocessing.misc
    - gms_preprocessing.model
    - gms_preprocessing.options
    - gms_preprocessing.processing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitext.gfz-potsdam.de/geomultisens/gms_preprocessing
  summary: GeoMultiSens - Scalable Multi-Sensor Analysis of Remote Sensing Data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
